### ISSUE TITLE
suddenly can't find a command

### ISSUE THREAD

**Issue by guijan** [hectorm/docker-qemu-haiku#1]
It seems the Haiku system of this docker image suddenly can't find the "meson" command I installed to it.

Here are 2 Github Actions runs of the same commit:
https://github.com/guijan/libobsd/runs/5764380361?check_suite_focus=true
https://github.com/guijan/libobsd/runs/5695801783?check_suite_focus=true

The older one just works, the newer one says "bash: line 1: meson: command not found"

**Comment by korli** [comment]
I noticed this today also. Installing haiku_devel sadly indicates a reboot is required.

**Comment by korli** [comment]
I added a reboot with this step, and it worked.
```
- name: 'Reboot and wait until the VM is ready'
        run: 'vmshell shutdown -r & timeout 600 vmshell exit 0'
```

**Comment by guijan** [comment]
I can confirm rebooting works. It should be added do the README.

**Comment by hectorm** [comment]
Thanks for letting me know about this issue, I have added a clarification to the readme.

**Comment by korli** [comment]
@hectorm would it be possible to regenerate the docker image, so that it's synched with the current beta3 hotfix?

**Comment by hectorm** [comment]
The latest release of this image is rebuilt weekly, just yesterday it was rebuilt. Is it necessary to rebuild it today as well?

**Comment by korli** [comment]
No, weekly is OK. I wasn't aware of this. Thanks!

**Comment by korli** [comment]
@guijan be sure to update the image name at https://github.com/guijan/libobsd/blob/b75f6e823a891c3aac2e37215476d66b84d801d0/.github/workflows/build-and-test.yml#L113 with docker.io/hectorm/qemu-haiku:latest

**Comment by guijan** [comment]
Thank you for the heads up, updated.

**Comment by madebr** [comment]
I'm also seeing this error in recent haiku logs of SDL.
For example, [this workflow run](https://github.com/libsdl-org/SDL/actions/runs/4032937794/jobs/6933129159) failed with `cmake: command not found`.

I've tried to apply the suggestion mentioned at https://github.com/hectorm/docker-qemu-haiku/issues/1#issuecomment-1084220596,
but then the workflow keeps spinning at the next job.
See [this workflow run](https://github.com/libsdl-org/SDL/actions/runs/4035256665/jobs/6937050627).

**Comment by hectorm** [comment]
Hi @madebr, I have done some debugging and it seems that the VM gets stuck in the shutdown process.

![](https://user-images.githubusercontent.com/852266/215322258-21b2a72e-87c2-451d-9684-a149e72d15b6.png)

I tried restarting the QEMU service with runit but found a bug where it never restarts because the netcat command used to send the shutdown instruction to the VM has no timeout specified. I have fixed this bug in the latest release and updated the restart command in the readme to:
```sh
sv force-restart qemu && timeout 600 vmshell exit 0
```

This way it tries to shutdown the machine in a graceful way first, and if that doesn't work, runit sends a SIGKILL.

**Comment by hectorm** [comment]
I also clarify that if the image is rebuilt, it is no longer necessary to restart it after installing packages.

I have a schedule to rebuild the last tag every Monday, but if this happens again and you don't want to wait for Monday, just ping me, it doesn't cost me anything to run the pipeline again.

**Comment by madebr** [comment]
I can wait another day :)
Thanks for bringing a solution this fast.

**Comment by madebr** [comment]
The message indicating it needs a reboot has indeed disappeared.
Can this message re-appear anytime soon or is it gone forever?
Is it safe(r) to restart the VM anyhow?

In https://github.com/libsdl-org/SDL/actions/runs/4039760426/jobs/6944793103,
I run the suggested `sv force-restart qemu && timeout 600 vmshell exit 0` to restart.
But it fails with a non-zero return code.

**Comment by korli** [comment]
The message will reappear anytime a hotfix commit is pushed at on the release branch https://cgit.haiku-os.org/haiku/log/?h=r1beta4 . It happens rarely.

**Comment by hectorm** [comment]
@korli is right. The image is rebuilt every week with the latest updates from the r1beta4 branch, but if there have been any hotfixes since the last rebuild, a reboot is required.

If you want to be sure, you can always reboot, it doesn't take too long compared to the rest of the pipeline execution.

@madebr, could you try using this command to restart the VM instead?
```sh
sv force-restart qemu; timeout 600 vmshell exit 0
```

**Comment by madebr** [comment]
> @madebr, could you try using this command to restart the VM instead?
> 
> ```shell
> sv force-restart qemu; timeout 600 vmshell exit 0
> ```

I tried `sv -w 600 force-restart qemu` yesterday and it just sleeped 10 minutes before failing.
https://github.com/libsdl-org/SDL/actions/runs/4039849649/jobs/6944964106
I suppose that's a similar command?

**Comment by hectorm** [comment]
The problem is that `sv force-restart qemu` returns a non-zero exit code if it had to force a restart due to a timeout. That's why the command I gave you initially fails and the one you gave me in your example also fails.

The last command I gave you should work. At least it does in my tests.
https://github.com/hectorm/SDL/blob/a694f7cbd37c91f121eead59c96f6f39eae09bd4/.github/workflows/haiku.yml#L23
https://github.com/hectorm/SDL/actions/runs/4046433136/jobs/6959210983

**Comment by madebr** [comment]
Thanks for explaining it all to me!
If the CI is happy, I'm happy ;)

**Comment by madebr** [comment]
Looks like the last suggestions still allows for a non-zero return code to leak through.
https://github.com/libsdl-org/SDL/actions/runs/4062065435/jobs/6992695804
Perhaps the command should be
```
sv force-restart qemu || true; timeout 600 vmshell exit 0
```

**Comment by guijan** [comment]
`|| true;` could be abbreviated to just `;`.

**Comment by madebr** [comment]
> `|| true;` could be abbreviated to just `;`.

That is the command that is failing in https://github.com/libsdl-org/SDL/actions/runs/4062065435/jobs/6992695804.

```
sv force-restart qemu; timeout 600 vmshell exit 0
```

**Comment by guijan** [comment]
Sorry, it appears I don't understand a shell with errexit like I thought.

**Comment by hectorm** [comment]
Oh, I forgot that the GitHub CI uses `set -e` by default, the correct command would be the one @madebr points out in https://github.com/hectorm/docker-qemu-haiku/issues/1#issuecomment-1411818528.
