### ISSUE TITLE
Reboot hangs 

### ISSUE THREAD

**Issue by jackburton79** [hectorm/docker-qemu-haiku#8]
It seems that with the new beta5 image , if I try to reboot the vm (using the command supplied with the instructions) after installing packages, that whole process hangs.
I realize this could be a haiku bug.

**Comment by jackburton79** [comment]
I had to remove reboot here:
https://github.com/jackburton79/bescreencapture/blob/master/.github/workflows/build.yml

**Comment by hectorm** [comment]
It seems that after installing the `haiku_devel` package the VM loses network connection if `virtio-net-pci` is used, I have not been able to reproduce this problem with `e1000`. It seems to be a bug in Haiku. I will switch to `e1000` for now.

**Comment by jackburton79** [comment]
Good catch. I just noticed issues with virtio NIC on my vm, too.
Thanks for your great work!

**Comment by jackburton79** [comment]
It seems there are virtio issues on NICs and Storage controllers, too

**Comment by hectorm** [comment]
What issues have you found with storage controllers?

**Comment by jackburton79** [comment]
> What issues have you found with storage controllers?

In my VMs, I noticed I often get hangs on boot if I set the storage controllers/disk to be virtio.
Moreover, I still get hangs on reboot with this container after your latest changes.
Example: the build action here: https://github.com/jackburton79/bescreencapture/actions/workflows/build.yml

hangs on reboot vm:
![image](https://github.com/user-attachments/assets/d3788e63-6c3b-49f3-87eb-fc766fd0957a)

**Comment by hectorm** [comment]
I have released a new version with a second round of fixes, for now I will use an IDE drive, also `haiku_devel` is now installed by default.

**Comment by jackburton79** [comment]
Thanks! Will try as soon as possibile

**Comment by jackburton79** [comment]
Hi, it seems reboot still doesn't work.
Have you got a scenario where you reboot the vm and it works, so I use the same command ?

**Comment by hectorm** [comment]
It's strange, I made a fork of BeScreenCapture for testing and I can only reproduce this behavior in the GitHub CI, locally the same commands work fine. I'll need more time to determine the cause.

**Comment by hectorm** [comment]
I think the reboot process is corrupting the filesystem after installing packages. I have not been able to reproduce this locally but I was able to connect to the GitHub CI runner using a reverse shell and do some testing.

![](https://github.com/user-attachments/assets/78daeae5-6acf-4a00-a2b1-5db28df8d39d)

It seems that if you run `sync` before rebooting the problem no longer occurs, could you try restarting the VM on the CI with this command?
```sh
vmshell sync; sv force-restart qemu ||:; timeout 600 vmshell exit 0
```

After this change I was able to build BeScreenCapture 8 times in a row without errors, although I can't guarantee that the problem is completely solved, we'll see.

**Comment by jackburton79** [comment]
I guess that force-restart doesn't do a clean shutdown, that's why it corrupts the file system.
Isn't there a restart command which triggers an acpi restart instead ?
Anyway, I'm going to try to sync beforehand, thank you!

**Comment by hectorm** [comment]
Actually `force-restart` [does an ACPI shutdown](https://github.com/hectorm/docker-qemu-haiku/blob/master/scripts/service/qemu/control/t) but if the VM takes more than 7 seconds it sends a KILL signal. I use `force-restart` because sometimes Haiku gets stuck in the shutdown process (like now).

This wait time is the default of runit, I will increase it to 20 seconds to give a little more time.

**Comment by jackburton79** [comment]
That works fine. Thank you. Let's close this
